[package]
name = "airc"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
rand = "0.9"
colored = "3.0"
async-std = "1"
regex = "1"
clap = { version = "4", features = ["derive"] }
zip = "2"
ratatui = "0"
crossterm = "0"
dirs = "6"
log = "0.4"
env_logger = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
thiserror = "1.0"
chrono = { version = "0.4", features = ["serde"] }
once_cell = "1.19"

